### ISSUE TITLE
[SPIKE] Roadmap to automation

### ISSUE THREAD

**Issue by jmargutt** [rodekruis/rumor-tracker#30]
### **Who requested this spike**
Jacopo. 

### **Functional or Technical Spike**
Functional

### **User Story**
As a Product Team
I want to automate the SML analysis as much as possible
So that I can scale up the service to more countries

### **Acceptance Criteria**
- [ ] Analysis requirements defined
- [ ] Roadmap to automation defined and issues created
- [ ] Presented to the team

### **Timebox**
2-4 hrs
